name: hart
version: 0.0.3+hotfix.m3
description: Hart — the heart of any Dart app
author: Yehor Lvivski <lvivski@gmail.com>
homepage: http://github.com/lvivski/hart
dependencies:
  unittest: ">=0.2.7"